#!/usr/bin/env bash

#
# Download solr config files from drupal.org for the docker image builds.
#

REALPATH="$(realpath $0)"

if [[ $# -ne 2 ]]; then
  echo "Usage:"
  echo "  $(basename $REALPATH) DRUPAL_MAJOR_VERSION SOLR_MAJOR_VERSION"
  echo "  Download and prepare solr config files for docker image build"
  echo "  example:  $(basename $REALPATH) 7 7"
  exit 1
fi

DRUPAL_VERSION=$1
SOLR_VERSION=$2
SOLR_CONF_VER="${SOLR_VERSION}.x"

cd $(dirname $REALPATH)/drupal${DRUPAL_VERSION}

# Get latest version for specified drupal version
latest_filename=$(wget -qO- http://drupal.org/project/search_api_solr \
  | grep -Eo "search_api_solr-${DRUPAL_VERSION}.x-[0-9\.]+.tar.gz" \
  | sort -V | tail -1)

# Download config for specified solr version
mkdir -pv conf
curl -S "https://ftp.drupal.org/files/projects/${latest_filename}" \
  | tar xvz search_api_solr/solr-conf/${SOLR_CONF_VER}
mv -v search_api_solr/solr-conf/${SOLR_CONF_VER}/* ./conf
rm -rfv search_api_solr
